### ISSUE TITLE
HA showing C instead of F

### ISSUE THREAD

**Issue by asucrews** [sanghviharshit/ha-mila#3]
Hello,

Great work on this! I really was hoping Mila API would be out by now.  But you solved this wounderfuly!

Just wondering if i missed something.  Buy HA is showing Mila Temps in C vs the App shoing in F.  My other Temp Sensors are reporting correctly in F.  Is there a setting I missed or what?

**Comment by Kennochas** [comment]
I don't see a setting for it as I just started using it and noticed the same thing.

Ha appears to have entity stuff for it here, so that the data can be presented to users in the right method. It may need to be hooked into, as for the most part HA stores and does everything in metric, and then localizes from there.

https://developers.home-assistant.io/docs/core/entity/climate/
https://developers.home-assistant.io/docs/core/entity/sensor

**Comment by sanghviharshit** [comment]
HA should localize based on your HA configuration.  Did you mean other temperature sensors in HA are in F, but Mila temperatures are in C?

**Comment by sanghviharshit** [comment]
The latest commit should fix it. You might have to delete and add the integration back to see the correct unit of measurement for the temperature sensor.

**Comment by Kennochas** [comment]
Just wanted to update to say thank you, I can confirm it is fixed. It did break historics, as they see the old before this version's data and changed it to be F without doing the conversion.

It's pretty obvious that's what happened, because the temp shot up from 20 to 75, so its probably not a huge deal.

**Comment by sanghviharshit** [comment]
Yes, It was a quick fix, but I don't actually know if it's possible to convert the historical data!
